---
- hosts: "{{ inventory_hostname }}"
  vars:
    inventory_hostname: tag_ansible_created
    name: ansible-created-instance
    ansible_user: openvpnas
    ansible_ssh_private_key_file: ~/.ssh/openvpn.pem
  gather_facts: True
  remote_user: openvpnas
  become: True
  tasks:
    - name: get ec2 gather_facts
      ec2_facts:
    - debug: var=ansible_ec2_instance_id

    - name: test connection
      ping:

    - name: install python python-pexpect from package (necessary for ansible expect module)
      apt: name={{ item }} state=installed update_cache=yes force=yes
      with_items:
        - python
        - python-pexpect
    
    - name: get to root
      shell: sudo su 

    - name: run initialization script
      expect:
        command: ovpn-init
        # echo: yes
        responses:
          "(?i)delete existing configuration[^\r\n]*: ?$": "DELETE"
          "(?i)indicate your agreement[^\r\n]*: ?$": "yes"
          "(?i)enter for default[^\r\n]*: ?$": ""
          "(?i)license key[^\r\n]*: ?$": ""

    - name: set password
      expect:
        command: passwd openvpn
        echo: no
        responses:
          "(?i)password": "openvpn"

    - name: find openvpn_as directory
      raw: ls /usr/local | grep openvpn_as >> /root/test_results.log

    - name: is openvpnas service up and running?
      raw: service openvpnas status | head | grep openvpnas.service >> /root/test_results.log

    - name: pid checks
      raw: ps aux | grep openvpnas >> /root/test_results.log

    - name: choose local authentication
      shell: /usr/local/openvpn_as/scripts/sacli --key auth.module.type --value local ConfigPut
    
    - name: Access server warm restart 
      shell: /usr/local/openvpn_as/scripts/sacli start

    - name: add user named testuser
      shell: /usr/local/openvpn_as/scripts/sacli -u testuser -k type -v user_connect UserPropPut

    - name: add admin user named admin
      shell: /usr/local/openvpn_as/scripts/sacli -u admin -k prop_superuser -v true UserPropPut

    - name: restart openvpnas service
      service: 
        name: openvpnas
        state: restarted

    - name: add password for testuser
      shell: /usr/local/openvpn_as/scripts/sacli --user testuser --new_pass thisisapassword SetLocalPassword

    - name: add password for admin
      shell: /usr/local/openvpn_as/scripts/sacli --user admin --new_pass adminpassword SetLocalPassword
    
    - name: Access server warm restart 
      shell: /usr/local/openvpn_as/scripts/sacli start

    - name: test authentication for users added
      shell: /usr/local/openvpn_as/scripts/confdba -us >> /root/test_results.log

    - name: change tunnel cipher (client)
      shell: /usr/local/openvpn_as/scripts/sacli -k vpn.client.config_text -v AES-256-CBC ConfigPut

    - name: change tunnel cipher (server)
      shell: /usr/local/openvpn_as/scripts/sacli -k vpn.server.config_text -v AES-256-CBC ConfigPut

    - name: add user-specific access controls - testuser nat to 10.0.0.0/24
      shell: /usr/local/openvpn_as/scripts/sacli -u testuser -k access_to.0 --value "+NAT:10.0.0.0/24" UserPropPut

    - name: add user-specific access controls - admin route to 192.168.33.0/24
      shell: /usr/local/openvpn_as/scripts/sacli -u admin -k access_to.0 --value "+ROUTE:192.168.33.0/24" UserPropPut

    - name: restart openvpnas service
      service: 
        name: openvpnas
        state: restarted
        
    - name: view all users in AS local auth
      shell: /usr/local/openvpn_as/scripts/confdba -a >> /root/test_results.log

    - name: view vpn status output
      shell: /usr/local/openvpn_as/scripts/sacli vpnstatus >> /root/test_results.log

    - name: fetch test_results.log
      fetch:
        src: /root/test_results.log
        dest: /tmp/as_test_results.log
        flat: yes

    - name: cd /home/openvpnas 
      shell: cd /home/openvpnas 

    - name: generate client profile for testuser
      shell: /usr/local/openvpn_as/scripts/sacli --user testuser GetUserLogin > testuser.ovpn

    - name: fetch testuser.ovpn 
      fetch:
        src: /home/openvpnas/testuser.ovpn 
        dest: /tmp/testuser.ovpn
        flat: yes