---
- hosts: "{{ inventory_hostname }}"
  vars:
    inventory_hostname: tag_ansible_created
    name_tag: ansible-created-instance
    ansible_user: openvpnas
    ansible_python_interpreter: python
    ansible_connection: local
    ansible_ssh_private_key_file: ~/.ssh/openvpn.pem
    region: us-west-1
  gather_facts: False
  remote_user: openvpnas
  become: True
  tasks:
    - name: get ec2 gather_facts
      ec2_facts:

    - name: set instance set_fact
      set_fact:
        host: "{{ name_tag }}"

    - name: terminate instance after test
      local_action:
        module: ec2
        region: "{{ region }}" 
        state: 'absent'
        instance_ids: "{{ ec2_id}}"
