---
- hosts: "{{ inventory_hostname }}"
  vars:
    inventory_hostname: tag_ansible_created
    name: ansible-created-instance
    ansible_user: openvpnas
    ansible_ssh_private_key_file: ~/.ssh/openvpn.pem
  gather_facts: True
  remote_user: openvpnas
  become: True
  tasks:
    - name: get ec2 gather_facts
      ec2_facts:
    - debug: var=ansible_ec2_instance_id

    - name: upgrade to AS 2.1.12
      apt:
        deb: http://swupdate.openvpn.org/as/openvpn-as-2.1.12-Ubuntu16.amd_64.deb
